urban_airflow_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../../infra_platform/duckdb_data/warehouse_dev.duckdb
      threads: 4

    preprod:
      type: duckdb
      path: ../../../infra_platform/duckdb_data/warehouse_preprod.duckdb
      threads: 4

    prod:
      type: duckdb
      path: ../../../infra_platform/duckdb_data/warehouse_prod.duckdb
      threads: 4