name: 'urban_airflow_analytics'
version: '1.0.0'

profile: 'urban_airflow_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  urban_airflow_analytics:
    staging:
      +schema: urban_airflow_analytics
      +materialized: table
    intermediate:
      +schema: urban_airflow_analytics
      +materialized: table
    mart:
      +schema: urban_airflow_analytics
      +materialized: table

on-run-start:
  - |
    {% if target.name in ['preprod', 'prod'] %}
    attach '{{ env_var("DBT_DEV_WAREHOUSE_PATH") }}' as dev_db;
    {% endif %}