name: CI (Lint only)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check .

      - name: Install sqlfluff
        run: pip install sqlfluff sqlfluff-templater-dbt

      - name: Run sqlfluff lint
        run: |
          sqlfluff lint analytics/dbt/urban_airflow_analytics/models \
            --dialect duckdb \
            --exclude-rules L019