name: Deploy dbt models

on:
  # Trigger when changes in dbt folder are merged into main
  push:
    branches: ["main"]
    paths:
      - "analytics/dbt/**"
  
  release:
    types: [published]

  # Allow manual runs from GitHub Actions UI
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install dbt-duckdb

      # Pick environment based on trigger
      - name: Run dbt build (preprod on merge, prod on release)
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Deploying to preprod..."
            dbt build --target preprod --profiles-dir ./analytics/dbt
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Deploying to prod..."
            dbt build --target prod --profiles-dir ./analytics/dbt
          else
            echo "Manual run: defaulting to preprod"
            dbt build --target preprod --profiles-dir ./analytics/dbt
          fi

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v4
        with:
          name: warehouse
          path: |
            infra_platform/duckdb_data/warehouse_preprod.duckdb
            infra_platform/duckdb_data/warehouse_prod.duckdb