name: Deploy dbt models

on:
  # Trigger when changes in dbt folder are merged into main
  pull_request:
    branches: ["main"]
    paths:
      - "analytics/dbt/**"
  
  release:
    types: [published]

  # Allow manual runs from GitHub Actions UI
  workflow_dispatch:

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: analytics/dbt/urban_airflow_analytics

    env:
      DBT_PROFILES_DIR: ../
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install dbt-duckdb

      - name: Set DB target
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Deploying to preprod..."
            echo "DBT_TARGET=preprod" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "Deploying to prod..."
            echo "DBT_TARGET=prod" >> $GITHUB_ENV
          fi

      - name: Init DuckDB database file
        run: |
          mkdir -p ../../../infra_platform/duckdb_data
          python - <<'PYCODE'
          import duckdb, os
          target = os.environ['DBT_TARGET']
          path = f"../../../infra_platform/duckdb_data/warehouse_{target}.duckdb"
          dev_path = "../../../infra_platform/duckdb_data/warehouse_dev.duckdb"
          # init target DB
          con = duckdb.connect(path)
          con.execute("create schema if not exists main;")
          con.close()
          print(f"Initialized {path}")
          # also init dev DB for sources
          if not os.path.exists(dev_path):
            con = duckdb.connect(dev_path)
            con.execute("create schema if not exists raw;")
            con.close()
            print(f"Initialized {dev_path}")
          PYCODE
          
      - name: Run dbt build
        run: dbt build

      - name: Upload DuckDB artifact
        uses: actions/upload-artifact@v4
        with:
          name: warehouse_${{ env.DBT_TARGET }}
          path: infra_platform/duckdb_data/warehouse_${{ env.DBT_TARGET }}.duckdb