name: Publish Dev DuckDB

on:
  schedule:
    - cron: "0 2 * * *"    # every day at 02:00 UTC
  workflow_dispatch:       # allow manual trigger from Actions tab

jobs:
  upload-dev-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload dev DB
        uses: actions/upload-artifact@v4
        with:
          name: warehouse_dev
          path: infra_platform/duckdb_data/warehouse_dev.duckdb