services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports: ['9000:9000', '9001:9001']
    volumes: ['minio_data:/data']
    networks:
      - data-platform
    
volumes: { minio_data: {} }

networks:
  data-platform:
    external: true